### ISSUE TITLE
Can't load OpenAPI document.

### ISSUE THREAD

**Issue by geoffsmith82** [paolo-rossi/OpenAPI-Delphi#3]
I am trying to load a swagger file with the code below.  When comparing the output to the input file, under the paths, it is missing the http methods and everything below that.  Am I doing something wrong?

```
   document := TOpenAPIDocument.Create(TOpenAPIVersion.v303);
   LJSON := TJSONObject.ParseJSONValue(TFile.ReadAllText('D:\Programming\codegeneration\Demos\DelphiSwaggerCodeGen\demo3api.json')) as TJSONObject;
   LReader := TNeonDeserializerJSON.Create(LConfig);
   LReader.JSONToObject(document, LJSON);

   SynEditClientPas.Text := TNeon.ObjectToJSONString(Document, LConfig);
```

**Comment by geoffsmith82** [comment]
[demo3api original.txt](https://github.com/paolo-rossi/OpenAPI-Delphi/files/10473287/demo3api.original.txt)
[demo3api written back.txt](https://github.com/paolo-rossi/OpenAPI-Delphi/files/10473295/demo3api.written.back.txt)

**Comment by paolo-rossi** [comment]
Hi Geoffrey,

I want to start saying that I'm looking at your issue and for a way to resolve it but I want to remark a few points:

- I built this library with the sole intent to *generate* an OpenAPI document from a convenient Delphi class (TOpenAPIDocument)  without struggling (too much) with the "craziness" :-) of the OpenAPI 3 specification.
- Loading (deserializing) a OpenAPI document was not my goal, especially because the OpenAPI specification is very broad and you can find very very complex documents that is nearly impossible to load into a Delphi standard class.

That said, I I find the task intriguing and challenging so I'm going to give it a try but probably, sooner or later, I will run into some "limitations" on the Delphi part (likely on the openapi examples, openapi callbacks, and openapi extensions) .

Last, can I ask you what are you trying to do? So I can get a better picture in order to prioritize some tasks?

Paolo.

**Comment by geoffsmith82** [comment]
Hi Paolo,
I'm working on a code generator.  I made significant contributions to https://github.com/marcelojaloto/SwagDoc , a swagger reader/writer.  

Some of the other Delphi projects with open API I have found are

https://github.com/landgraf-dev/openapi-delphi-generator
https://github.com/CleverComponents/OpenApi-Delphi
https://github.com/joaoduarte19/OpenApi4D

They all seem to be half implemented or I can't get them to compile.

I actually think that OpenAPI is better than Swagger as the fixed some of the issues up and made it easier to deal with (still not super easy though).
